package com.prosa.hbn;
// Generated 11/11/2017 10:12:45 AM by Hibernate Tools 3.6.0



/**
 * TblSrrBanco generated by hbm2java
 */
public class TblSrrBanco  implements java.io.Serializable {


     private Integer id;
     private String codigoBanco;

    public TblSrrBanco() {
    }

    public TblSrrBanco(String codigoBanco) {
       this.codigoBanco = codigoBanco;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCodigoBanco() {
        return this.codigoBanco;
    }
    
    public void setCodigoBanco(String codigoBanco) {
        this.codigoBanco = codigoBanco;
    }




}


